### ISSUE TITLE
Can't get extension to work

### ISSUE THREAD

**Issue by ajithfort** [codemix/yii2-localeurls#37] opened 2015-07-21 09:14 UTC
![screenshot from 2015-07-21 14 39 05](https://cloud.githubusercontent.com/assets/11402503/8797011/8867c7a8-2fb6-11e5-991e-a8c7631ae053.png)
![screenshot from 2015-07-21 14 40 13](https://cloud.githubusercontent.com/assets/11402503/8797020/8c6da962-2fb6-11e5-9ad7-8cd12507e5b4.png)

as you can see when i added the following code in main.php(advanced app)
 'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['en-US', 'en', 'fr', 'de', 'es-*'],
            'enableDefaultLanguageUrlCode' => true,
            'enableLanguagePersistence' => false,
        ],
my whole website got errors, images are not displaying, layout all displaced. what am i missing apart from the code that i inserted in main.php

**Comment by ajithfort** [comment] 2015-07-21 09:30
also my local language is 'MALAYALAM' so i tried like this 
'languages' => ['en-US', 'en', 'fr', 'de', 'es-*','ml-IN'],
and typed url as 192.168.1.3/~user/urshow/frontend/web/index.php/ml-in?r=index.php
so i thought website would change to 'malayalam' but no change happened.

**Comment by mikehaertl** [comment] 2015-07-21 10:29
Weird, because the URLs you show are not pretty URLs. But this extension requires `enablePrettyUrl` to be set: 

https://github.com/codemix/yii2-localeurls/blob/master/UrlManager.php#L119

Did you disable ord override this somehow?

**Comment by ajithfort** [comment] 2015-07-21 10:33
i haven't enabled pretty url

**Comment by mikehaertl** [comment] 2015-07-21 10:36
Then how do you get this URL `.../frontend/web/index.php?r=site/home`? With pretty URLs you should never see any query parameters in your URLs.

**Comment by ajithfort** [comment] 2015-07-22 11:08
sorry for my late reply. if i had enabled pretty url then my url would be like
/frontend/web/index.php/site/home.

**Comment by mikehaertl** [comment] 2015-07-22 11:29
Pretty URLs are automatically enabled, otherwhise you'd see an exception. If it still doesn't work, you should check, which URL is used for your images. Most important: Please show some code, how you create the image URLs on your site.

**Comment by ajithfort** [comment] 2015-07-27 12:05
i think problem is with pretty url. i will update about my progress

**Comment by ajithfort** [comment] 2015-07-31 04:50
ok i have enabled pretty url and this is my code  
'urlManager' => [
			 'class' => 'codemix\localeurls\UrlManager',
			 'languages' => ['en-US', 'en', 'fr', 'de', 'es-*'],
			 'enableDefaultLanguageUrlCode' => true,
			 'enableLanguagePersistence' => false,
			'class' => 'yii\web\UrlManager',
			'enablePrettyUrl' => true,
			'showScriptName' => false,
			 'rules' => array(
                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
        ),
        ],

**Comment by ajithfort** [comment] 2015-07-31 04:54
ok got it actually i had declared class twice inside url manager. i removed it and got it working.

**Comment by ajithfort** [comment] 2015-07-31 05:04
if i type my url like this http://192.168.1.3/~user/urshow/frontend/web/es/site/home
i should get my website in spanish isn't it? but no change is happening, its still in english. why?

**Comment by mikehaertl** [comment] 2015-07-31 07:16
Yes it should, as this is the main feature of this extension - and this definitely works. Must still be some problem on your side. Maybe some AJAX request or something which sets the language back immediately after it was changed to `es`. You should use some debugging tool like firebug or Chrome's developer extension and examine the network requests.

I'm closing this for now. If you think there's a problem with this extension, please open a new issue and provide example code to reproduce the issue.

**Closed by mikehaertl** 2015-07-31 07:16 UTC
