### ISSUE TITLE
The page keeps redirecting

### ISSUE THREAD

**Issue by frank96100** [codemix/yii2-localeurls#158] opened 2020-04-27 16:10 UTC
[Nginx]

```
location / {
                index index.php;
                try_files $uri $uri/ /index.php?$args;
                #if (!-e $request_filename){
                #       rewrite ^/(.*) /index.php last;
                #}
        }
        
        #nginx is normally accessed through php-fpm
        #location ~ \.php$ {
        #       include fastcgi_params;
        #       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #       fastcgi_pass 127.0.0.1:9000;
        #       #fastcgi_pass unix:/var/run/php5-fpm.sock;
        #       try_files $uri =404;
        #}

        #Always redirect
        location ~ \.php$ {
                proxy_set_header  Host $host;
                proxy_set_header  X-Real-IP  $remote_addr;
                proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
                #proxy_connect_timeout 300;
                #proxy_send_timeout   300;
                #proxy_read_timeout   300;
                #send_timeout 300;
                proxy_pass https://127.0.0.1:4433;
        }
```

[Apache]

```
<Directory "/var/www/html">
    Options FollowSymLinks
    AllowOverride All
    Require all granted

    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . index.php
    RewriteRule ^index.php/ - [L,R=404]
</Directory>
```

what should I do?
Thank you.

**Comment by mikehaertl** [comment] 2020-04-27 17:11
I don't understand: You have Nginx in front of php-fpm and then Apache in front of Nginx?

But to be honest: I can not provide any help with server setup and I don't think that your problem has much to do with our library here. Try to enable debugging in Nginx and Apache then use `curl -I [url]` to open your app and see what's going on.

I'm closing this for now. If you think something is broken with our library, please provide a clear (small) example to reproduce the issue and why you think it is caused by our library.

**Closed by mikehaertl** 2020-04-27 17:11 UTC
