### ISSUE TITLE
issue or not - illegal redirection

### ISSUE THREAD

**Issue by robov** [codemix/yii2-localeurls#121] opened 2017-10-08 07:35 UTC
I am doing some pentesting and I noticed when I append this to the end of the url   ie 
```
xxx.com/en-us/http%3a//adaonsa2inf/a%3ffile/ HTTP/1.1
```
then the site redirects to the hacked url 
```
http://adaonsa2inf/a?file/%20HTTP/1.1?file%2F_HTTP%2F1_1=
```
When I use a fake language like
```
.. /xxxxxxxxxx/http%3a//adaonsa2inf/a%3ffile/ HTTP/1.1
```
then the redirection is not happening and ends up normally on the index

However I am not sure if this is in your plugin or on my code....

**Comment by mikehaertl** [comment] 2017-10-08 15:14
Not sure, where you see an issue here. Behaves exactly as expected, no?

**Comment by robov** [comment] 2017-10-08 16:54
When I go to
```
xxx.com/en-us/http%3a//adaonsa2inf/a%3ffile/ HTTP/1.1
```
the site is redirected to
```
http://adaonsa2inf/a?file/%20HTTP/1.1?file%2F_HTTP%2F1_1=
```
This allowed phisers to create a valid looking url (domain is correct), and then eventually redirect when someone clicked on the link

it should go to:
```
xxx.com/
```
Because of the params are just incorrect

**Comment by mikehaertl** [comment] 2017-10-09 06:41
Now I see, but I can not reproduce this. I'm not sure if this could be caused by the library.

Could you please start with a clean app template and only add the minimum configuration and see if you still  can reproduce the issue? Then please paste that configuration here.

**Comment by robov** [comment] 2017-10-09 08:58
I am also not sure if it is caused by the library or not.. I do not have a clean template available so it might take a while before I can check if this also is there on a clean template

**Comment by mikehaertl** [comment] 2018-01-17 09:43
Closing this as there was no further feedback.

**Closed by mikehaertl** 2018-01-17 09:43 UTC
