### ISSUE TITLE
A widget to be used with your extension.

### ISSUE THREAD

**Issue by soap** [codemix/yii2-localeurls#75] opened 2016-08-12 05:01 UTC
First of all, thanks to your great extension. It is easy to use and configurable. However for me or someone it is very hard to make a language switcher widget like example shown in your documentation. 

So I made the yii2-language-switcher widget to be used with this extension. It can display in dropdown mode or button mode. I used in in my projects but not thoroughly tested yet.

https://github.com/soap/yii2-language-switcher. Attached below is an example of dropdown mode.

![yii2-language-switcher](https://cloud.githubusercontent.com/assets/1073690/17613157/59f127c0-6084-11e6-9b76-b69270f25bf7.png)

**Comment by mikehaertl** [comment] 2016-08-12 13:35
Thanks, we may consider adding a note to the README.

Closing this for now as it's not a bug.

**Closed by mikehaertl** 2016-08-12 13:35 UTC
