### ISSUE TITLE
URL encoding

### ISSUE THREAD

**Issue by panchenkodv** [codemix/yii2-localeurls#70] opened 2016-05-07 15:00 UTC
Hi!
Everything works as expected but there is a case that when redirectToLanguage($language) is called $url is encoded. It make wrong redirect to wrong page.
This is help for me Yii::$app->getResponse()->redirect(urldecode($url));
But it's possible decode URL by some config param, that tells decode or not URL in the redirect?

**Comment by mikehaertl** [comment] 2016-05-08 10:21
Can you give me an example, please?

**Comment by panchenkodv** [comment] 2016-05-09 06:14
URL manager config

'class' => 'codemix\localeurls\UrlManager',
    // List all supported languages here
    // Make sure, you include your app's default language.
    'languages' => ['ru' => 'ru-RU', 'uk' => 'uk-UA'],
    'enableLanguagePersistence' => false,
    'enableLanguageDetection' => false,
    'enablePrettyUrl'   =>  true,
    'showScriptName'    =>  false,
    'rules'             =>  [
        ''                  =>  'site/index',
        '<url:(.*)>'        =>  'site/renderpage',
    ]

If I try url "/ru/bizhuteriya/kolca" it redirect me to "/bizhuteriya%2Fkolca" and I got 404 error.

**Comment by mikehaertl** [comment] 2016-05-09 07:07
How do you create this URL?

**Comment by panchenkodv** [comment] 2016-05-09 07:23
type in browser

**Comment by mikehaertl** [comment] 2016-05-09 07:28
Let me explain a bit more: With your URL setup above, you use a single parameter `url` to match the complete URL. You seem to have URLs that where not created with Yii, because if you try this:

```
echo \yii\helpers\Url::to(['site/renderpage', 'url' => 'abc/def']);
```

You will get `/abc%2Fdef`. So Yii will always encode all slashes in your `url` parameter, which is expected behavior. So you can not really create URLs for your URL schema above in Yii.

What do you know about your URLs? Do they always follow the same pattern? Like `/part1/part2/part3`? Then you should rather create a URL rule like this:

```
'<part1>/<part2>/<part3>' => 'site/renderpage',
```

In your action you can still create your `$url` as `$url = "$part1/$part2/$part3";`. If your URL is more dynamic, maybe you need a couple of rules instead:

```
'<part1>/<part2>/<part3>' => 'site/renderpage',
'<part1>/<part2>' => 'site/renderpage',
'<part1>' => 'site/renderpage',
```

**Comment by panchenkodv** [comment] 2016-05-09 09:00
Now max numbers of part is 4.
'<part1>/<part2>/<part3>/<part4>' => 'site/renderpage'

There are no limits to the depth of nested parts links. Because each piece is characterized by nested categories, and can be an unlimited number of such investments.
I can not predict how many parts I might need. In addition, each category stores the full path to the database from the parent and ending oneself.

**Comment by mikehaertl** [comment] 2016-05-09 09:36
Well, this extension is only working for URLs that can be created with Yii. In your case, the URLs come from some external source and can not be created by the framework (unless you add URL rules as described above).

This is probably the same issue as #57. There we discussed to maybe revert the changes in b4c9629e - for the cost of making the code more ugly again. I'm not sure yet, if we really want to do that. Maybe there's a better workaround.

**Comment by alexantr** [comment] 2017-01-04 15:29
I see only one solution - create custom class whitch implements UrlRuleInterface

```php
'rules' => [
    '' => 'site/index',
    ['class' => 'app\components\PagesUrlRule'],
    // other rules
],
```

**Comment by panchenkodv** [comment] 2017-01-04 18:16
I make fork of this repo, change code as I needed and enjoy it.

**Comment by maxneh** [comment] 2017-03-06 05:54
I have nested Url how the creator of the issue. 
I solved the problem by adding to this rule `'encodeParams' => false,`

**Comment by mikehaertl** [comment] 2017-05-10 06:51
I'm closing this for now as I still think it's not something we can / should fix in this extension.

**Closed by mikehaertl** 2017-05-10 06:51 UTC
