### ISSUE TITLE
url manager slug pattern problem

### ISSUE THREAD

**Issue by vc7deo** [codemix/yii2-localeurls#61] opened 2016-02-25 17:27 UTC
this is my **urlmanager **settings

```
        'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['en', 'ar'],
            'enableDefaultLanguageUrlCode' => false,
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                '<alias:index|login>' => 'site/<alias>', 
                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>', 
                '<controller:\w+>/<action:\w+>/<slug:[A-Za-z0-9 -_.]+>' => '<controller>/<action:\w+>/slug',
                '<controller:\w+>/<slug:[A-Za-z0-9 -_.]+>' => '<controller>/slug',
                'defaultRoute' => '/site/index',
            ],
        ],
```
i have 2 languages English and Arabic

so i made simple language switcher like this

```
        $route = Yii::$app->controller->route;
        $params = !empty($_GET) ? '?'.http_build_query($_GET) : '';
        $link = '/'.$route.$params;
```
and in the navbar i add the language switcher

```
<?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];
    if(Yii::$app->language == 'ar'){
        $menuItems[] = ['label' => 'English', 'url' => Url::to([$link, 'language'=>'en'])];
    } else {
        $menuItems[] = ['label' => 'العربية', 'url' => Url::to([$link, 'language'=>'ar'])];
    }
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>
```

but my url generating like this

http://localhost/multi/backend/web/ar/post/slug?slug=my-long-slug-post  ----- Arabic
http://localhost/multi/backend/web/post/slug?slug=my-long-slug-post      ----- English

http://stackoverflow.com/questions/35574561/yii2-createurl-is-duplicating-the-route/35580052
this is my first attempt to create the simple switcher and i have a duplicating problem so after lots of trying i got above solution it's working well except the slug

**Comment by mikehaertl** [comment] 2016-02-25 18:09
Why do you use ` $params = !empty($_GET) ? '?'.http_build_query($_GET) : '';`? This will obviously create the `?slug=...` part of the URL.

**Comment by mikehaertl** [comment] 2016-02-25 18:11
Also look at #57 where a similar issue was reported. I've since added test cases that show, that URL creation with slugs works just fine. Check the `SlugTestCase` where this is tested.

**Comment by mikehaertl** [comment] 2016-02-25 20:17
Ok, I think this is a problem with your URL rules. 

First in your rule  `'<controller:\w+>/<action:\w+>/<slug:[A-Za-z0-9 -_.]+>' => '<controller>/<action:\w+>/slug'` you should not have `:\w+` in the action part on the right side. Also that `slug` doesn't really belong there.

You should also put the more specific rules on top, because when parsing a request, the first matching rule will be used.

I've done a test here and everything works as expected. My configuration is:

```
[
    'language' => 'en',
    'components' => [
        'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['en','de','fr'],
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                '<controller:\w+>/<action:\w+>/<slug:[A-Za-z0-9 -_.]+>' => '<controller>/<action>',
            ],
        ],
...
]
```

I have a simple test action in my `SiteController` like:

```
    public function actionDemo($slug)
    {
        return $this->render('index');
    }
```

And I've used the `LanguageDropdown` as shown in the [README](https://github.com/codemix/yii2-localeurls#example-language-selection-widget).

If I go to `site/demo/some-slug` the page will render fine and the dropdown will have links like 

* `/de/site/demo/some-slug`
* `/fr/site/demo/some-slug`

**Comment by vc7deo** [comment] 2016-02-26 03:58
Thanks for your quick response.the problem is with language switcher i made as you said

i have 2 languages so i need a simple switcher .

```
   $route = Yii::$app->controller->route;
   $params = $_GET;
   array_unshift($params, '/'.$route);
```
```
  <?php if(Yii::$app->language == 'ar'){ ?>
  <?= Html::a('English', [Yii::$app->urlManager->createUrl($params), 'language'=>'en']); ?>
  <?php }else{?>
  <?= Html::a('Arabic', [Yii::$app->urlManager->createUrl($params), 'language'=>'ar']); } ?>
```

i tried part of the code taken from your language drop down its not working .

**Comment by mikehaertl** [comment] 2016-02-26 08:03
Again, I'm pretty sure, this is a problem with your URL rules. So please first try to make it work without the localeurl extension (i.e. remove the `codemix\localeurls\UrlManager` and according configuration). You need to be able to create a slug URL with `\yii\helpers\Url::to(['your/action', 'slug' =>'some-slug')`. This doesn't work with the rules you have.

I'm closing this for now, because I can't reproduce any issue. If you find out, that URL creation works correctly without our class but fails with localeurls let us know and I will have another look.

**Closed by mikehaertl** 2016-02-26 08:03 UTC

**Comment by vc7deo** [comment] 2016-02-26 12:36
Thanks...
i tried everything nothing suceed this is the site i developed using yii2 used above default  urlrule

http://flywingzdestination.com/package/malaysia-3-nights-4-days

i just need a simple switcher when we are in English site show a switcher link like [Arabic](url) and viceversa.the problem is i'm generating the url its like 

http://localhost/**multi/backend/web**/en/**multi/backend/web**/ar/post/slug?slug=my-long-slug-post

as explained just above my post

i dont know why its repeating the **multi/backend/web**

**Comment by mikehaertl** [comment] 2016-02-26 13:14
Can you create a correct slug URL witout our extension?

**Comment by vc7deo** [comment] 2016-03-14 04:44
hii after lot of trying i got solution for my first problem

```
   $route = Yii::$app->controller->route;
    if(Yii::$app->language == 'ar'){
        $_GET['language'] = 'en';
    }else{
        $_GET['language'] = 'ar';
    }
    $params = $_GET;
    array_unshift($params, '/'.$route);
```

and for link

```
  <?php if(Yii::$app->language == 'ar'){ ?>
  <?= Html::a('English', Yii::$app->urlManager->createUrl($params)); ?>
  <?php }else{?>
  <?= Html::a('Arabic', Yii::$app->urlManager->createUrl($params)); } ?>
```

Now i have one more problem.I cant hide action name when using slug

i cant use url like this

http://localhost/multi/backend/web/ar/post/my-long-slug-post

when switch it'll redirect to

http://localhost/multi/backend/web/post/slug?slug=my-long-slug-post

.But when i use default Url manager it works fine using below rules

'<controller:\w+>/<slug:[A-Za-z0-9 -_.]+>' => '<controller>/slug',

and you can see the live example used above rule

http://flywingzdestination.com/package/malaysia-3-nights-4-days

**Comment by mikehaertl** [comment] 2016-03-14 08:03
@vc7deo Hmm. Can you provide a simple test configuration that I can use to reproduce the issue? Preferably you should use a clean, simple fresh yii application and only add so much configuration there until the problem appears. Then post what you've changed in the default configuration here.

**Comment by vc7deo** [comment] 2016-03-14 16:02
@mikehaertl .. i use fresh yii2 application for this.Here is my Urlmanager configuration.When i comment first 3 lines it works perfectly.

```
        'urlManager' => [
           'class' => 'codemix\localeurls\UrlManager',
           'languages' => ['en', 'ar'],
            'enableDefaultLanguageUrlCode' => false,
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                '<alias:index|login>' => 'site/<alias>', 
                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>', 
                '<controller:\w+>/<action:\w+>/<slug:[A-Za-z0-9 -_.]+>' => '<controller>/<action>',
                '<controller:\w+>/<slug:[A-Za-z0-9 -_.]+>' => '<controller>/slug',
                'defaultRoute' => '/site/index',
            ],
        ],
```

**Comment by mikehaertl** [comment] 2016-03-14 17:42
This is still a problem with your URL rules. The following 2 rules match the same URL format:

```
'<controller:\w+>/<action:\w+>' => '<controller>/<action>', 
'<controller:\w+>/<slug:[A-Za-z0-9 -_.]+>' => '<controller>/slug',
```

When you create a URL, Yii will go through all URL rules and use the first matching rule. So for example:

```
$url = Url::to(['somecontroller/slug', 'slug' => 'blabla'])
```

The first rule that matches the route is `<controller:\w+>/<action:\w+>`. Yii will stop there and use this rule. You need to make sure, that your URL rules are unambiguous and that more special rules are listed first.

All this has nothing to do with this extension. I'd suggest that you carefully read again about URL creation and parsing in the Yii guide here: http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html

**Comment by vc7deo** [comment] 2016-03-15 05:55
@mikehaertl .. as i said before its working with default urlmanager

i used same url rules the below live site
this is controller without action(controller/slug)
http://flywingzdestination.com/package/malaysia-3-nights-4-days

and this controller with action
http://flywingzdestination.com/site/contact

both working perfectly

if i use **controller/action/slug** then this urlmanager works.but it would be better if i can hide the action from it

**Comment by mikehaertl** [comment] 2016-03-15 07:49
I'm still missing the code you used to create the URL. The URL itself doesn't help me to debug your problem.
